version: '2.1'
services:
  postgres:
    image: postgres:9.3

  conjur:
    image: registry.tld/conjur:0.1.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', '-X OPTIONS', 'http://localhost']
    #   interval: 2s
    #   timeout: 1s
    #   retries: 5

  tester:
    build: .
    volumes:
      - ./spec/reports:/src/conjur-api/spec/reports
      - ./features/reports:/src/conjur-api/features/reports
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
