version: '2.1'
services:
  pg:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - pg

  tester:
    build: .
    volumes:
      - ./spec/reports:/src/conjur-api/spec/reports
      - ./features/reports:/src/conjur-api/features/reports
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber

  dev:
    build: .
    entrypoint: bash
    volumes:
      - .:/src/conjur-api
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
